/**
 * Cascade Apartment 3 - Stripe Connect Integration
 * Handles: Stripe Connect onboarding, payment processing,
 * payment intents, and checkout flow
 *
 * NOTE: This module requires the Stripe.js library to be loaded:
 * <script src="https://js.stripe.com/v3/"></script>
 *
 * ============================================================
 * TWO-PARTY STRIPE CONNECT MODEL
 * ============================================================
 *
 * ACCOUNT 1 — Admin Platform Account (Stripe Connect platform)
 *   - The admin/management company creates a standard Stripe account
 *   - Connect is enabled in Settings → Connect settings
 *   - This account receives all guest payments first
 *   - Keeps the management fee (application_fee_amount)
 *   - Publishable key and Connect Client ID come from this account
 *
 * ACCOUNT 2 — Property Owner Connected Account (Express)
 *   - typhoon.tall69@gmail.com creates a Stripe Express account
 *   - Onboarded via an Account Link generated by the platform server
 *   - Receives their share automatically via transfer_data.destination
 *   - Has their own Stripe dashboard to view transfers and manage payouts
 *
 * PAYMENT FLOW (Destination Charges):
 *   Guest pays $1,000
 *     → Platform receives $1,000
 *     → application_fee_amount: $150  (15% admin management fee)
 *     → transfer_data.destination: 'acct_owner_id'  → Owner gets $850
 *     → Stripe fees (~$29.30) come out of the platform's $150 share
 *
 * SERVER-SIDE EXAMPLE (Node.js):
 *
 *   const paymentIntent = await stripe.paymentIntents.create({
 *     amount: 100000,                   // $1,000.00 in cents
 *     currency: 'aud',
 *     payment_method_types: ['card'],
 *     application_fee_amount: 15000,    // 15% = $150.00 admin fee
 *     transfer_data: {
 *       destination: 'acct_conn_9ZyXwVuTsRq',  // owner's connected acct
 *     },
 *     metadata: {
 *       booking_id: 'CA3-20260215',
 *       property: 'Cascade Apartment 3',
 *     },
 *   });
 *   // Return paymentIntent.client_secret to the client
 *
 * OWNER ONBOARDING (server-side):
 *
 *   // 1. Create Express account for owner
 *   const account = await stripe.accounts.create({ type: 'express' });
 *
 *   // 2. Generate onboarding link and email to owner
 *   const accountLink = await stripe.accountLinks.create({
 *     account: account.id,
 *     refresh_url: 'https://yoursite.com/admin/payments',
 *     return_url:  'https://yoursite.com/admin/payments?connected=true',
 *     type: 'account_onboarding',
 *   });
 *   // Redirect owner to: accountLink.url
 *
 * WEBHOOKS TO HANDLE:
 *   - payment_intent.succeeded  → mark booking as paid
 *   - transfer.created          → log owner transfer amount
 *   - account.updated           → update owner account status
 */

(function() {
  'use strict';

  const StripeConnect = {
    stripe: null,
    elements: null,
    cardElement: null,

    // Configuration (would be set from server/environment)
    config: {
      publishableKey: 'pk_test_your_stripe_publishable_key',
      locale: 'en-AU',
      currency: 'aud',
      appearance: {
        theme: 'stripe',
        variables: {
          colorPrimary: '#0f2744',
          colorBackground: '#ffffff',
          colorText: '#2d2926',
          colorDanger: '#e74c3c',
          fontFamily: 'Inter, sans-serif',
          spacingUnit: '4px',
          borderRadius: '8px',
        }
      }
    },

    /**
     * Initialize Stripe
     */
    init() {
      if (typeof Stripe === 'undefined') {
        console.warn('Stripe.js not loaded. Payment processing unavailable.');
        this.showPlaceholder();
        return;
      }

      try {
        this.stripe = Stripe(this.config.publishableKey);
        this.createElements();
      } catch (e) {
        console.warn('Failed to initialize Stripe:', e.message);
        this.showPlaceholder();
      }
    },

    /**
     * Create Stripe Elements for card input
     */
    createElements() {
      const cardContainer = document.getElementById('stripe-card-element');
      if (!cardContainer || !this.stripe) return;

      this.elements = this.stripe.elements({
        appearance: this.config.appearance
      });

      this.cardElement = this.elements.create('card', {
        style: {
          base: {
            fontSize: '16px',
            color: '#2d2926',
            fontFamily: 'Inter, sans-serif',
            '::placeholder': {
              color: '#b8b0a4',
            },
          },
          invalid: {
            color: '#e74c3c',
          },
        }
      });

      this.cardElement.mount('#stripe-card-element');

      // Handle real-time validation
      this.cardElement.on('change', (event) => {
        const errorEl = document.getElementById('card-errors');
        if (errorEl) {
          errorEl.textContent = event.error ? event.error.message : '';
        }
      });
    },

    /**
     * Show placeholder when Stripe is not loaded
     */
    showPlaceholder() {
      const cardContainer = document.getElementById('stripe-card-element');
      if (cardContainer) {
        cardContainer.innerHTML = `
          <div style="padding: 16px; border: 2px dashed var(--color-light); border-radius: 8px; text-align: center; color: var(--color-gray);">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="margin: 0 auto 8px;">
              <rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/>
            </svg>
            <p style="font-size: 14px; margin-bottom: 4px;">Stripe Payment Element</p>
            <p style="font-size: 12px; opacity: 0.7;">Connect your Stripe account to enable payments</p>
          </div>
        `;
      }
    },

    /**
     * Process payment via Stripe Connect Destination Charges.
     *
     * In production this method should:
     *   1. POST booking data to your server endpoint (/api/create-payment-intent)
     *   2. Server creates a PaymentIntent with application_fee_amount and
     *      transfer_data.destination pointing to the owner's connected account
     *   3. Server returns the client_secret
     *   4. Call stripe.confirmCardPayment(clientSecret, { payment_method: { card, billing_details } })
     *
     * Payment split (15% admin / 85% owner by default — configurable in admin):
     *   - application_fee_amount = amount * managementFeePct  → stays with platform
     *   - transfer_data.destination = ownerConnectedAccountId → auto-transferred to owner
     */
    async processPayment(bookingData) {
      if (!this.stripe || !this.cardElement) {
        throw new Error('Stripe not initialized');
      }

      const managementFeePct = bookingData.managementFeePct || 0.15; // 15% default
      const ownerConnectedAccountId = bookingData.ownerConnectedAccountId || 'acct_conn_9ZyXwVuTsRq';

      const applicationFeeAmount = Math.round(bookingData.amount * managementFeePct);
      const ownerTransferAmount  = bookingData.amount - applicationFeeAmount;

      const billingDetails = {
        name: bookingData.cardholderName,
        email: bookingData.email,
        address: {
          line1: bookingData.address,
          city: bookingData.city,
          state: bookingData.state,
          postal_code: bookingData.postcode,
          country: bookingData.country || 'AU',
        }
      };

      // Production server call would look like:
      //
      // const response = await fetch('/api/create-payment-intent', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({
      //     amount: bookingData.amount,          // in cents
      //     currency: this.config.currency,
      //     application_fee_amount: applicationFeeAmount,
      //     transfer_destination: ownerConnectedAccountId,
      //     booking_id: bookingData.bookingId,
      //     metadata: { property: 'Cascade Apartment 3' }
      //   }),
      // });
      // const { clientSecret } = await response.json();
      //
      // const result = await this.stripe.confirmCardPayment(clientSecret, {
      //   payment_method: {
      //     card: this.cardElement,
      //     billing_details: billingDetails,
      //   },
      // });
      // if (result.error) throw new Error(result.error.message);

      console.log('Stripe Connect Destination Charge (simulated):', {
        amount: bookingData.amount,
        currency: this.config.currency,
        application_fee_amount: applicationFeeAmount,
        'transfer_data.destination': ownerConnectedAccountId,
        adminKeeps: applicationFeeAmount,
        ownerReceives: ownerTransferAmount,
        billingDetails
      });

      // Simulate successful payment
      return {
        success: true,
        paymentIntentId: 'pi_simulated_' + Date.now(),
        status: 'succeeded',
        applicationFeeAmount,
        ownerTransferAmount,
        ownerConnectedAccountId
      };
    },

    /**
     * Start Stripe Connect onboarding for the property owner.
     *
     * In production, the server creates an Express account and Account Link:
     *
     *   const account = await stripe.accounts.create({ type: 'express' });
     *   const link = await stripe.accountLinks.create({
     *     account: account.id,
     *     refresh_url: 'https://yoursite.com/admin/payments',
     *     return_url:  'https://yoursite.com/admin/payments?connected=true',
     *     type: 'account_onboarding',
     *   });
     *   res.json({ url: link.url });
     *
     * Then redirect the owner to link.url for Stripe's hosted onboarding.
     */
    async startOnboarding() {
      console.log('Starting Stripe Connect owner onboarding...');

      // In production: call /api/create-connect-account then redirect to returned URL
      const onboardingUrl = 'https://connect.stripe.com/setup/s/demo';

      window.CascadeApp?.showToast('Generating owner onboarding link...', 'info');

      // In production: window.location.href = onboardingUrl;
      return { url: onboardingUrl };
    },

    /**
     * Check Connect account status
     */
    async checkAccountStatus(accountId) {
      // In production, call your server to check the connected account status
      return {
        accountId: accountId || 'acct_demo',
        chargesEnabled: true,
        payoutsEnabled: true,
        detailsSubmitted: true,
        businessType: 'company',
        created: '2026-01-15'
      };
    },

    /**
     * Create a refund
     */
    async createRefund(paymentIntentId, amount, reason) {
      console.log('Refund would be processed:', {
        paymentIntentId,
        amount,
        reason
      });

      return {
        success: true,
        refundId: 'rf_simulated_' + Date.now(),
        status: 'succeeded'
      };
    }
  };

  // ============================================
  // Checkout Form Handler
  // ============================================
  function initCheckoutForm() {
    const form = document.getElementById('checkoutForm');
    if (!form) return;

    form.addEventListener('submit', async (e) => {
      e.preventDefault();

      const submitBtn = form.querySelector('button[type="submit"]');
      const originalText = submitBtn?.textContent;
      if (submitBtn) {
        submitBtn.disabled = true;
        submitBtn.textContent = 'Processing...';
      }

      try {
        const formData = new FormData(form);
        const data = Object.fromEntries(formData);

        const result = await StripeConnect.processPayment({
          cardholderName: data.cardholderName,
          email: data.email,
          address: data.address,
          city: data.city,
          state: data.state,
          postcode: data.postcode,
          country: data.country,
          amount: parseInt(data.amount) || 0
        });

        if (result.success) {
          window.CascadeApp?.showToast('Payment successful!', 'success');

          // Merge guest data (from booking form) with payment data, save for confirmation
          const ref = window.CascadeApp?.BookingEngine?.generateReference() || 'CA3-' + Date.now();
          const pending = JSON.parse(sessionStorage.getItem('ca3_pending_booking') || '{}');
          const amountCents = parseInt(data.amount) || 0;
          const totalFormatted = amountCents
            ? new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(amountCents / 100)
            : '';
          const depositCents = Math.round(amountCents * 0.3);
          const depositFormatted = depositCents
            ? new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(depositCents / 100)
            : '';

          const confirmedBooking = {
            ...pending,
            ref,
            guestName:    pending.guestName  || data.cardholderName || 'Guest',
            guestEmail:   pending.guestEmail || data.email || '',
            totalAmount:  totalFormatted,
            depositAmount: depositFormatted,
            paymentStatus: 'paid',
            confirmedAt:  new Date().toISOString(),
          };
          sessionStorage.setItem('ca3_confirmed_booking', JSON.stringify(confirmedBooking));

          window.location.href = 'confirmation.html?ref=' + encodeURIComponent(ref);
        }
      } catch (error) {
        window.CascadeApp?.showToast(error.message || 'Payment failed. Please try again.', 'error');
      } finally {
        if (submitBtn) {
          submitBtn.disabled = false;
          submitBtn.textContent = originalText;
        }
      }
    });
  }

  // ============================================
  // Stripe Connect Admin Handler
  // ============================================
  function initStripeAdmin() {
    const connectBtn = document.getElementById('stripeConnectBtn');
    if (connectBtn) {
      connectBtn.addEventListener('click', async () => {
        await StripeConnect.startOnboarding();
      });
    }

    const disconnectBtn = document.getElementById('stripeDisconnectBtn');
    if (disconnectBtn) {
      disconnectBtn.addEventListener('click', () => {
        if (confirm('Are you sure you want to disconnect your Stripe account?')) {
          window.CascadeApp?.showToast('Stripe account disconnected', 'warning');
        }
      });
    }
  }

  // ============================================
  // Initialize
  // ============================================
  function init() {
    StripeConnect.init();
    initCheckoutForm();
    initStripeAdmin();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  window.CascadeApp = window.CascadeApp || {};
  window.CascadeApp.StripeConnect = StripeConnect;
})();
